// <auto-generated />
using System;
using IndividualWorkAPI.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IndividualWorkAPI.Migrations
{
    [DbContext(typeof(ContextDatabase))]
    [Migration("20260422142343_IndividualWorkAPI")]
    partial class IndividualWorkAPI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndividualWorkAPI.Models.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("commentId"));

                    b.Property<string>("commentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("parentCommentId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.Property<int>("videoId")
                        .HasColumnType("integer");

                    b.HasKey("commentId");

                    b.HasIndex("parentCommentId");

                    b.HasIndex("userId");

                    b.HasIndex("videoId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Login", b =>
                {
                    b.Property<int>("loginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("loginId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("loginId");

                    b.HasIndex("userId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Reaction", b =>
                {
                    b.Property<int>("reactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reactionId"));

                    b.Property<int?>("commentId")
                        .HasColumnType("integer");

                    b.Property<int>("reactionType")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.Property<int>("videoId")
                        .HasColumnType("integer");

                    b.HasKey("reactionId");

                    b.HasIndex("commentId");

                    b.HasIndex("videoId");

                    b.HasIndex("userId", "videoId")
                        .IsUnique();

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roleId"));

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("roleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Session", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("sessionId"));

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("sessionId");

                    b.HasIndex("userId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Subscription", b =>
                {
                    b.Property<int>("subscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("subscriptionId"));

                    b.Property<int>("channelId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("subscriberId")
                        .HasColumnType("integer");

                    b.HasKey("subscriptionId");

                    b.HasIndex("channelId");

                    b.HasIndex("subscriberId", "channelId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("channelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("dateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("userId");

                    b.HasIndex("roleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Video", b =>
                {
                    b.Property<int>("videoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("videoId"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("privacyStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("publishDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("s3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("thumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("videoId");

                    b.HasIndex("userId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Comment", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("parentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndividualWorkAPI.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndividualWorkAPI.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("videoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Login", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Reaction", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.Comment", "comment")
                        .WithMany()
                        .HasForeignKey("commentId");

                    b.HasOne("IndividualWorkAPI.Models.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndividualWorkAPI.Models.Video", "video")
                        .WithMany()
                        .HasForeignKey("videoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("comment");

                    b.Navigation("video");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Session", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Subscription", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.User", "channel")
                        .WithMany()
                        .HasForeignKey("channelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndividualWorkAPI.Models.User", "subscriber")
                        .WithMany()
                        .HasForeignKey("subscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("channel");

                    b.Navigation("subscriber");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.User", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.Video", b =>
                {
                    b.HasOne("IndividualWorkAPI.Models.User", "user")
                        .WithMany("Videos")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("IndividualWorkAPI.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
